/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_anomaly_831808_6.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_831808_1[] = { "anomaly" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_831808_2_axes[] = { 0, 1, 2, 3, 4 };
const uint32_t ei_dsp_config_831808_2_axes_size = 5;
ei_dsp_config_raw_t ei_dsp_config_831808_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    5, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_831808_2[5] = { 131.51204297465662, 180.7890337872249, 27.89949455671413, 43.89615276705834, 29.940606459750924 };
const float ei_dn_standard_scaler_scale_831808_2[5] = { 0.13138105092029886, 0.09924732409930534, 0.39368697962359067, 0.3505562520753489, 0.4116754471591867 };
const float ei_dn_standard_scaler_var_831808_2[5] = { 57.934136338848774, 101.52251961377173, 6.452052561691109, 8.13737941412802, 5.900517030545339 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_831808_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_831808_2,
    .mean_data_len = 5,
    .scale_data = (float *)ei_dn_standard_scaler_scale_831808_2,
    .scale_data_len = 5,
    .var_data = (float *)ei_dn_standard_scaler_var_831808_2,
    .var_data_len = 5
};
ei_data_normalization_t ei_data_normalization_config_831808_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_831808_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_831808_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_831808_1[ei_dsp_blocks_831808_1_size] = {
    { // DSP block 2
        2,
        5, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_831808_2, // pointer to config struct
        ei_dsp_config_831808_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_831808_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_831808_2, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_831808_6 = {
    .implementation_version = 1,
    .model = tflite_anomaly_831808_6,
    .model_size = tflite_anomaly_831808_6_len,
    .arena_size = tflite_anomaly_831808_6_arena_size
};

ei_learning_block_config_anomaly_gmm_t ei_learning_block_config_831808_6 = {
    .implementation_version = 1,
    .block_id = 6,
    .anom_axis = ei_classifier_anom_axes_831808_6,
    .anom_axes_size = 5,
    .graph_config = (void*)&ei_config_graph_831808_6
};

const uint8_t ei_learning_blocks_831808_1_size = 1;
const uint32_t ei_learning_block_831808_6_inputs[1] = { 2 };
const uint8_t ei_learning_block_831808_6_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_831808_1[ei_learning_blocks_831808_1_size] = {
    {
        6,
        &run_gmm_anomaly,
        (void*)&ei_learning_block_config_831808_6,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_831808_6_inputs,
        ei_learning_block_831808_6_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_831808_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_831808_1[ei_postprocessing_blocks_831808_1_size] = {
    {
        .block_id = 6,
        .type = EI_CLASSIFIER_MODE_ANOMALY_GMM,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_anomaly,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 6
    },
};

const uint8_t freeform_outputs_831808_1_size = 0;

uint32_t *freeform_outputs_831808_1 = nullptr;

const ei_impulse_t impulse_831808_1 = {
    .project_id = 831808,
    .project_owner = "abdo1994",
    .project_name = "abdo1994-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 5,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 5,
    .dsp_input_frame_size = 1 * 5,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_831808_1_size,
    .dsp_blocks = ei_dsp_blocks_831808_1,

    .learning_blocks_size = ei_learning_blocks_831808_1_size,
    .learning_blocks = ei_learning_blocks_831808_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_831808_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_831808_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "KPH + TOP_SPEED + S1_SECONDS + S2_SECONDS + S3_SECONDS",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_GMM,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories_831808_1,
    .results_type = EI_CLASSIFIER_TYPE_NONE,
    .freeform_outputs_size = freeform_outputs_831808_1_size,
    .freeform_outputs = freeform_outputs_831808_1
};

ei_impulse_handle_t impulse_handle_831808_1 = ei_impulse_handle_t( &impulse_831808_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_831808_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_831808_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_831808_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_831808_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
